### PR TITLE
edc-qol model

### PR DESCRIPTION
**Pull request by frdrckaman**
Create a model for EDC-QOL

### CODE REVIEW

**Comment by erikvw** [comment]
@frdrckaman, this looks good. just a few minor things.

1. please sort `constants` in alphabetical order
2. since you declared these text strings as constants, you should use them in the `choices`.
3. the tests are failing on the linter. Black/isort. Have a look. See also the `tox.ini`.

**Comment by frdrckaman** [comment]
@erikvw I have sort constants, use them on choices and fix the test

**Comment by erikvw** [comment]
@frdrckaman, could you run isort and black before you push. the tests should pass if the linter passes.

**Comment by frdrckaman** [comment]
@erikvw i format witj black and isort

**Comment by erikvw** [comment]
1. add yourself to the AUTHORS file
2. can you add an `auths.py`. See `edc_msni.auths.py` 
3. in `.github/workflows/build.yml` please change `django-version: ['3.2', 'dev']` to `django-version: ['3.2']`

**Pull request merged**
